# GitLab CI/CD Pipeline for Spring Boot 3 Enterprise Project

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_REGISTRY: "registry.example.com"
  K8S_NAMESPACE: "springboot3-enterprise"
  SONAR_HOST: "http://sonarqube.example.com"

# 缓存配置
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - target/

# 流水线阶段
stages:
  - validate
  - build
  - test
  - quality
  - package
  - deploy-dev
  - deploy-test
  - deploy-staging
  - deploy-prod

# 模板定义
.maven_template: &maven_template
  image: maven:3.9-eclipse-temurin-17
  before_script:
    - export MAVEN_HOME=/usr/share/maven
    - mvn --version

.docker_template: &docker_template
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

.kubectl_template: &kubectl_template
  image: bitnami/kubectl:latest
  before_script:
    - kubectl version --client
    - echo $KUBE_CONFIG | base64 -d > kubeconfig
    - export KUBECONFIG=./kubeconfig

# ==================== Validate 阶段 ====================
validate:code:
  <<: *maven_template
  stage: validate
  script:
    - mvn validate
    - mvn dependency:resolve
  only:
    - merge_requests
    - main
    - develop

# ==================== Build 阶段 ====================
build:compile:
  <<: *maven_template
  stage: build
  script:
    - mvn clean compile -DskipTests
  artifacts:
    paths:
      - target/
      - "*/target/"
    expire_in: 1 day
  only:
    - merge_requests
    - main
    - develop

# ==================== Test 阶段 ====================
test:unit:
  <<: *maven_template
  stage: test
  script:
    - mvn test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura/coverage.xml
    paths:
      - "*/target/jacoco.exec"
      - "*/target/site/jacoco/"
    expire_in: 7 days
  only:
    - merge_requests
    - main
    - develop

test:integration:
  <<: *maven_template
  stage: test
  services:
    - postgres:16-alpine
    - redis:7-alpine
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_pass
    SPRING_PROFILES_ACTIVE: test
  script:
    - mvn verify -P integration-test
  artifacts:
    reports:
      junit:
        - "*/target/failsafe-reports/TEST-*.xml"
  only:
    - merge_requests
    - main
    - develop

# ==================== Quality 阶段 ====================
quality:sonarqube:
  <<: *maven_template
  stage: quality
  script:
    - mvn sonar:sonar
      -Dsonar.projectKey=$CI_PROJECT_NAME
      -Dsonar.projectName=$CI_PROJECT_NAME
      -Dsonar.host.url=$SONAR_HOST
      -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - main
    - develop
  allow_failure: true

quality:dependency-check:
  <<: *maven_template
  stage: quality
  script:
    - mvn dependency-check:check
  artifacts:
    paths:
      - target/dependency-check-report.html
    expire_in: 7 days
  only:
    - main
    - develop
  allow_failure: true

# ==================== Package 阶段 ====================
package:jar:
  <<: *maven_template
  stage: package
  script:
    - mvn package -DskipTests -Drevision=$CI_COMMIT_SHORT_SHA
  artifacts:
    paths:
      - "*/target/*.jar"
    expire_in: 7 days
  only:
    - main
    - develop

package:docker:
  <<: *docker_template
  stage: package
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        echo "Building Docker image for $service"
        mvn jib:build -pl $service \
          -Djib.to.image=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -Djib.to.tags=latest \
          -Djib.to.auth.username=$DOCKER_USERNAME \
          -Djib.to.auth.password=$DOCKER_PASSWORD
      done
  only:
    - main
    - develop

# ==================== Deploy Dev 阶段 ====================
deploy:dev:
  <<: *kubectl_template
  stage: deploy-dev
  environment:
    name: development
    url: https://dev-api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        kubectl set image deployment/$service \
          $service=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -n $K8S_NAMESPACE-dev --record

        kubectl rollout status deployment/$service \
          -n $K8S_NAMESPACE-dev --timeout=5m
      done
  only:
    - develop

# ==================== Deploy Test 阶段 ====================
deploy:test:
  <<: *kubectl_template
  stage: deploy-test
  environment:
    name: test
    url: https://test-api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        kubectl set image deployment/$service \
          $service=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -n $K8S_NAMESPACE-test --record

        kubectl rollout status deployment/$service \
          -n $K8S_NAMESPACE-test --timeout=5m
      done
  only:
    - main
  when: manual

# ==================== Deploy Staging 阶段 ====================
deploy:staging:
  <<: *kubectl_template
  stage: deploy-staging
  environment:
    name: staging
    url: https://staging-api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        # 金丝雀发布：先部署 20% 流量
        kubectl set image deployment/$service-canary \
          $service=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -n $K8S_NAMESPACE-staging --record

        kubectl rollout status deployment/$service-canary \
          -n $K8S_NAMESPACE-staging --timeout=5m

        echo "Canary deployed, waiting for verification..."
        sleep 300  # 等待 5 分钟观察
      done
  only:
    - main
  when: manual

deploy:staging:promote:
  <<: *kubectl_template
  stage: deploy-staging
  environment:
    name: staging
    url: https://staging-api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        # 全量发布
        kubectl set image deployment/$service \
          $service=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -n $K8S_NAMESPACE-staging --record

        kubectl rollout status deployment/$service \
          -n $K8S_NAMESPACE-staging --timeout=5m
      done
  needs:
    - deploy:staging
  only:
    - main
  when: manual

# ==================== Deploy Prod 阶段 ====================
deploy:prod:canary:
  <<: *kubectl_template
  stage: deploy-prod
  environment:
    name: production
    url: https://api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        # 金丝雀发布：先部署 10% 流量
        kubectl set image deployment/$service-canary \
          $service=$DOCKER_REGISTRY/$service:$CI_COMMIT_SHORT_SHA \
          -n $K8S_NAMESPACE --record

        kubectl rollout status deployment/$service-canary \
          -n $K8S_NAMESPACE --timeout=5m

        echo "Production canary deployed, waiting for verification..."
        sleep 600  # 等待 10 分钟观察
      done
  only:
    - tags
  when: manual

deploy:prod:blue-green:
  <<: *kubectl_template
  stage: deploy-prod
  environment:
    name: production
    url: https://api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        # 蓝绿部署
        # 1. 部署绿色环境
        kubectl apply -f k8s/$service-deployment-green.yaml -n $K8S_NAMESPACE
        kubectl rollout status deployment/$service-green -n $K8S_NAMESPACE --timeout=5m

        # 2. 验证绿色环境
        kubectl run -it --rm test-pod --image=curlimages/curl --restart=Never -- \
          curl -f http://$service-green:8080/actuator/health

        # 3. 切换流量到绿色环境
        kubectl patch service $service -n $K8S_NAMESPACE \
          -p '{"spec":{"selector":{"version":"green"}}}'

        echo "Traffic switched to green environment"
        sleep 60

        # 4. 清理蓝色环境
        kubectl delete deployment $service-blue -n $K8S_NAMESPACE || true

        # 5. 重命名绿色为蓝色
        kubectl label deployment $service-green version=blue --overwrite -n $K8S_NAMESPACE
      done
  needs:
    - deploy:prod:canary
  only:
    - tags
  when: manual

# ==================== Rollback ====================
rollback:prod:
  <<: *kubectl_template
  stage: deploy-prod
  environment:
    name: production
    url: https://api.example.com
  script:
    - |
      for service in gateway auth-service user-service order-service product-service; do
        kubectl rollout undo deployment/$service -n $K8S_NAMESPACE
        kubectl rollout status deployment/$service -n $K8S_NAMESPACE --timeout=5m
      done
  only:
    - tags
  when: manual
